language: php

install:
  - composer install

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

jobs:
  include:
    - stage: test
      php: 7.2
      name: "coding standard"
      script:
        - composer check-cs
cache:
  directories:
    - node_modules
    - vendor

notifications:
  email:
    on_success: never
