language: php

php:
  - 7.3

install:
  - composer install
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - php artisan key:generate
  - npm install

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
env:
  - TRAVIS_NODE_VERSION="4"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output




