language: php

php:
  - 7.3
jobs:
  include:

    - stage: preprare
      name: install
      script:
        - composer install
        - php artisan key:generate
        - npm install


    - stage: deploy
      namae: 'Deploy to Github Pages'
      if: branch = master
        script:
          # import data
          - bin/console import -vvv
          # generate website to "/output" directory
          - vendor/bin/statie generate source -vvv

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: output

cache:
  directories:
    - node_modules
    - vendor

