language: php

install:
  - composer install

script: skip

jobs:
  include:
    - stage: test
      php: 7.2
      name: "Coding Standards"
      script:
        - composer check-cs

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
