language: php

php:
  - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - composer install
  - php artisan key:generate
  - npm install

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
    -
env:
  - TRAVIS_NODE_VERSION="4"
