language: php

php:
  - 7.3
install:
  - composer install
  - php artisan key:generate
  - npm install

script: skip
services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master



